name: Create Release
on:
  push:
    branches:
      - "*"
    tags:
      - 'v*'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    
    - name: Restore Packages
      run: nuget restore FanControl.LiquidCtl.sln

    - name: Build Solution
      run: msbuild.exe FanControl.LiquidCtl.sln /p:configuration="Release"

    - name: Create Release Archive
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        path: 'bin/Release'
        filename: 'bin/FanControl.LiquidCtl.${{github.ref_name}}.zip'
        exclusions: '*.xml *.pdb FanControl.Plugins.dll'
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: FanControl.LiquidCtl.${{github.ref_name}}.zip
        path: bin/FanControl.LiquidCtl.${{github.ref_name}}.zip

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: bin/FanControl.LiquidCtl.${{github.ref_name}}.zip
